language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
addons:
  sonarcloud:
    organization: "mongo-shaman"
    token:
      secure: ${SONAR_TOKEN} # encrypted value of your token
script:
  - sonar-scanner
